name: Deploy HTML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy files to nginx folder
        run: rsync -a -v --remove-source-files --delete-after --exclude=.github ./ /var/www/tuncatakan.com
